<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CakeTime.Application\CakeTime.Application.csproj" />
    <ProjectReference Include="..\CakeTime.Infrastructure\CakeTime.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Pages\MainPage.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\CalendarContent.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\EmptyEventListContent.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\EventAddContent.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\EventContentBase.xaml.cs">
      <DependentUpon>EventContentBase.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\EventEditContent.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\EventListContent.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\SettingsContent.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Update="Pages\MainPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\CalendarContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\EmptyEventListContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\EventAddContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\EventContentBase.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\EventEditContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\EventListContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\SettingsContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>

  <ItemGroup>
    <None Update="Pages\MainPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\CalendarContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\EmptyEventListContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\EventAddContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\EventEditContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\EventListContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\SettingsContent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

</Project>
